### ISSUE TITLE
Need guidance on using setup.py

### ISSUE THREAD

**Issue by cyndaqua** [SkyTemple/py-desmume#33]
Hi, I would like to use py-desmume but I'm having trouble. Notably, I believe I'm supposed to build desmume, but when I ran setup.py with python setup.py install, it returned an error that it could not find the specified path. Is there a guide on how to set this up? Thanks.

**Comment by theCapypara** [comment]
Hi! What error do you get? Did you try running `pip3 install -vvv`? That should output what goes wrong. You probably don't have Visual Studio installed, which is required for building under Windows or you don't have a GCC toolchain if you are building under Linux.

**Comment by cyndaqua** [comment]
When I run `pip3 install -vvv` inside of the `py-desmume-master`, I get this:

`C:\Users\cyndaqua\Desktop\DeSmuME\py-desmume-master>pip3 install -vvv
Using pip 22.3.1 from C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\site-packages\pip (python 3.10)
User install by explicit request
Created temporary directory: C:\Users\cyndaqua\AppData\Local\Temp\pip-build-tracker-vhkg8pgv
Initialized build tracking at C:\Users\cyndaqua\AppData\Local\Temp\pip-build-tracker-vhkg8pgv
Created build tracker: C:\Users\cyndaqua\AppData\Local\Temp\pip-build-tracker-vhkg8pgv
Entered build tracker: C:\Users\cyndaqua\AppData\Local\Temp\pip-build-tracker-vhkg8pgv
Created temporary directory: C:\Users\cyndaqua\AppData\Local\Temp\pip-install-xok5l3ma
ERROR: You must give at least one requirement to install (see "pip help install")
Exception information:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_internal\commands\install.py", line 344, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_internal\cli\req_command.py", line 458, in get_requirements
    raise CommandError(
pip._internal.exceptions.CommandError: You must give at least one requirement to install (see "pip help install")
Remote version of pip: 22.3.1
Local version of pip:  22.3.1
Was pip installed by pip? True
Removed build tracker: 'C:\\Users\\cyndaqua\\AppData\\Local\\Temp\\pip-build-tracker-vhkg8pgv'`

I have Visual Studio Community 2019 installed, and have built your fork of DeSmuME by launching the DeSmuME.sln, but the py-desmume said I was missing `libdesmume.dll` when I tried to execute the code in the quickstart section.

**Comment by theCapypara** [comment]
Ah sorry `pip install -vvv py-desmume` of course.

**Comment by theCapypara** [comment]
If you are trying to run this in editable mode (`-e` to pip install) you need to build the DLL manually. But unless you want to develop for py-desmume that's not neccesary.

**Comment by cyndaqua** [comment]
How do I build the dll manually?

**Comment by theCapypara** [comment]
You open the [`/desmume_src/desmume/src/frontend/interface/DeSmuME_Interface.vcxproj`](https://github.com/SkyTemple/desmume/blob/f321ae7d038bd9ba30585f8fa6a1dc1428aef5af/desmume/src/frontend/interface/windows/DeSmuME_Interface.vcxproj) file in Visual Studio and build the "Release" or "Release Fastbuild" config. That outputs the DLL under `__bins`. You rename that to `libdesmume.dll` and place it in the `/desmume` directory. You also copy the [SDL2.dll](https://github.com/SkyTemple/desmume/tree/f321ae7d038bd9ba30585f8fa6a1dc1428aef5af/desmume/src/frontend/interface/windows/SDL/lib) there.

You can also use MSBuild. For reference see https://github.com/SkyTemple/py-desmume/blob/master/setup.py#L121

You can also try forcing the build of the DLL even when using `-e` by stubbing out this class: https://github.com/SkyTemple/py-desmume/blob/master/setup.py#L58 or setting the value in it to False, etc.

**Comment by cyndaqua** [comment]
Thanks, that worked.
