### ISSUE TITLE
Build wheels for MacOS ARM64 (M1)

### ISSUE THREAD

**Issue by mike8699** [SkyTemple/py-desmume#55]
Now that [GitHub Actions supports MacOS M1](https://github.com/actions/runner-images/issues/9254), is there plans for `py-desmume` to build ARM64 wheels for Mac?

**Comment by DragnirMK** [comment]
We would really appreciate it

**Comment by theCapypara** [comment]
I can not get the macOS ARM build to work and need help:
https://github.com/SkyTemple/py-desmume/actions/runs/10857426943/job/30133834515

I don't understand why `ld` tries to link anything against `x86_64` libraries. There is nothing anywhere telling it to do so. `desmume-rs` and another Python project that uses it build fine under ARM so I really don't understand what's going on.

**Comment by theCapypara** [comment]
Okay for whatever reason the architecture needs to be explicitly set to `arm64` in `CPPFLAGS`. I don't get Apple sometimes, why does it default to x86 on a native ARM Mac? But okay.
